### PR TITLE
Fix config before begin behaviour

### PR DESCRIPTION
**Pull request by sandeepmistry**
Calling ```config``` before ```begin``` would result in DHCP address instead of the static configuration.

This was not up to spec. with the expected documented behaviour: https://www.arduino.cc/en/Reference/WiFi101Config

This patch disables DHCP if ```config``` is used. Also, includes some cleanup to the ```config``` API implementations to remove duplications.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
I've push a small additional change to only clear the local IP, subnet mask and gateway on disconnect, if DHCP is enabled.

**Comment by turkycat** [comment]
I've confirmed this resolves the issue I experienced! :gem:

**Comment by sandeepmistry** [comment]
Rebased and merged.

**Pull request closed without merging**
