### PR TITLE
Make reset pin optional

### PR DESCRIPTION
**Pull request by awatterott**
The EN and Reset pins are not necessary to use the WINC1500.
Currently there is only a check for an undefined EN pin and this PR adds also a check for the reset pin.

### CODE REVIEW

**Comment by ubergesundheit** [comment]
What is the status of this pull request?

I would really appreciate seeing this change in the official library for an upcoming device based on the ATWINC1500B!

**Comment by robarto** [comment]
Any news on the status here? I would be very glad to see the changes in the official library.

**Comment by sandeepmistry** [comment]
@awatterott thanks!

**Comment by awatterott** [comment]
@sandeepmistry thank you for accepting the PR.

**Pull request merged**
