### PR TITLE
Add TX buffer to WiFiUDP, rename _buffer to _recvBuffer

### PR DESCRIPTION
**Pull request by sandeepmistry**
Potential solution to #56.

* renamed ```WiFiUDP::_buffer``` to ```WiFiUDP::_rcvBuffer```
* added TX buffer for WiFiUDP writes

### CODE REVIEW

**Comment by sandeepmistry** [comment]
I am checking with Atmel to see if there is a way to buffer inside the WINC1500, so there might be an alternative for this in the future.

**Comment by cmaglie** [comment]
If there is no way to buffer directly in the WINC1500, this change looks good to me. :+1:

**Comment by sandeepmistry** [comment]
@cmaglie great, thanks for reviewing!

I forgot to mention the buffers sizes:

* AVR: 48 bytes
* non-AVR: 4224 bytes

**Comment by cmaglie** [comment]
> non-AVR: 4224 bytes

What about using 512?

4225 seems a lot to me given that the MTU for IP is 1500 I'd stay under that limit even if theoretically an IP network should be able to fragment/reassemble the UDP payload if it doesn't fit in a single IP packet, up to almost 64KB, this decrease reliability if the packets transits on the public network.

source http://stackoverflow.com/questions/1098897/what-is-the-largest-safe-udp-packet-size-on-the-internet

**Comment by sandeepmistry** [comment]
> What about using 512?

Agreed we should lower it, we should apply the same to the RX buffer. See: https://github.com/arduino-libraries/WiFi101/blob/master/src/socket/include/socket_buffer.h#L65

Looks like the MTU is 1400.

What do you think about lowering both to a fixed size instead of multiplying by ```SOCKET_BUFFER_NB```?

**Comment by cmaglie** [comment]
I'm wondering what this `SOCKET_BUFFER_NB` means, is it used somewhere else? It seems that `SOCKET_BUFFER_UDP_SIZE` represents the size of the buffer of a single socket and not a "cumulative" size shared among different sockets so, if this is the case, I agree with you to set them to a fixed size.

**Comment by sandeepmistry** [comment]
I only see ```SOCKET_BUFFER_NB``` being used in ```SOCKET_BUFFER_TCP_SIZE``` and ```SOCKET_BUFFER_UDP_SIZE```. Maybe we can make both fixed size then. On the non-limited RAM side for UDP I think we should go with UDP buffer size of the MTU (1400 bytes).

Also, maybe a multiple is needed to make up for the fact the WINC1500 does not buffer data internally when receiving data.

**Pull request merged**
