### PR TITLE
Additions to Adafruit_WINC1500 to allow sketch request for DNS IP

### PR DESCRIPTION
**Pull request by R3Electronics**
Updated Adafruit_WINC1500.h and Adafruit_WINC1500.cpp to add option to read assigned DNS server IP address from user sketch. Simple code additions to add public member and function to return DNS IP Address for user sketch.

Readme includes addtion to example printWifiStatus to show usage.

Richard. Hewitt (RH3).

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Hi @R3Electronics,

Thank you for submitting this pull request. However, this Github repo does not host the `Adafruit_WINC1500.h` and `Adafruit_WINC1500.cpp` files which you edited.

We'd be happy to review any equivalent changes that are made to `WiFi101.h` and `WiFi.cpp`. Please remote the `ReadMe` file as well.

Thanks.

**Comment by sandeepmistry** [comment]
I'm going to close this due to lack of activity. When the changes discussed in https://github.com/arduino-libraries/WiFi101/pull/87#issuecomment-240198619 are made we can re-open and re-discuss.

**Comment by R3Electronics** [comment]
Hi Sandeep,
 
I checked with Rick over at Adafruit and I think there is some confusion. Rick mentioned to create a pull request for this change in the WiFi101, which I did. He later mentioned this is where Adafruit fork their build from so he may have been wrong initially.
 
Should I have made the proposed changes to the WINC1500 library rather than the Adafruit_WINC1500 version?
 
Regards,
 
Richard.

 
Date: Wed, 7 Sep 2016 07:21:16 -0700

**Comment by sandeepmistry** [comment]
> Should I have made the proposed changes to the WINC1500 library rather than the Adafruit_WINC1500 version?

Hi @R3Electronics, it's up to you really. If you'd like to contribute to this version please do. The next release will include a `WiFi.setPins(...)` API to make it compatible with any WINC1500 based board.

**Pull request closed without merging**
